### ISSUE TITLE
I get an error when I execute ./joern-parse ./reveal_data

### ISSUE THREAD

**Issue by Fangweijun111** [VulScribeR/VulScribeR#1]
![image](https://github.com/user-attachments/assets/b23b8c50-3113-477f-91de-28c227705261)

**Comment by VulScribeR** [comment]
Hi, thanks for pointing it out. Joern's build files haven't been pushed and were ignored because of the git ignore file. Hence, it requires to be built with Gradle and Java 11. However, that's not needed as I have added the fully built joern to the replication package and you can download it from [here](https://github.com/VulScribeR/VulScribeR/releases/download/Release/joern.zip).

Download the built joern and replace it with the one(s) that are in the repo.

**Comment by VulScribeR** [comment]
Take a look at the Notes section here:

https://github.com/VulScribeR/VulScribeR/blob/main/code/readme.md

It should look like this (Java 11, no gradle installed): 
![image](https://github.com/user-attachments/assets/ce1d230b-84b6-424c-b121-5f8895f46b6f)

Note that parsed directory should be removed each time!
